Repository ucsb-cs156-f23/proj-organic-f23-6pm-3, pull requests merged in 2023-11, with the labels that each got.

#17 Added space in Footer
  frontend/src/main/components/Nav/Footer.js
  frontend/src/tests/components/Nav/Footer.test.js
  src/main/java/edu/ucsb/cs156/organic/controllers/UsersController.java
Labels: 5

#24 Course Form and Tests
  frontend/src/main/components/Courses/CourseForm.js
  frontend/src/stories/components/Courses/CourseForm.stories.js
  frontend/src/tests/components/Courses/CourseForm.test.js
Labels: Instructor Comment Fixed

#32 EPIC: B1 - Backend endpoints to toggle (PRIORITY)
  src/main/java/edu/ucsb/cs156/organic/config/SecurityConfig.java
  src/main/java/edu/ucsb/cs156/organic/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/organic/controllers/UsersController.java
  src/main/java/edu/ucsb/cs156/organic/entities/User.java
  src/test/java/edu/ucsb/cs156/organic/controllers/JobsControllerTests.java
  src/test/java/edu/ucsb/cs156/organic/controllers/UsersControllerTests.java
Labels: 10

#28 Table Component for Courses
  frontend/src/main/components/Courses/CoursesTable.js
  frontend/src/main/utils/courseUtils.js
  frontend/src/stories/components/Courses/CoursesTable.stories.js
  frontend/src/tests/components/Courses/ArticlesTable.test.js
  frontend/src/tests/utils/courseUtils.test.js
Labels: 10, Merge Candidate

#25 CRUD Operations B1 - POST/GET and Controllers
  src/main/java/edu/ucsb/cs156/organic/controllers/CoursesController.java
  src/main/java/edu/ucsb/cs156/organic/controllers/UserInfoController.java
  src/main/java/edu/ucsb/cs156/organic/repositories/StaffRepository.java
  src/test/java/edu/ucsb/cs156/organic/controllers/CoursesControllerTests.java
Labels: 10

#37 CRUD operations B3 - DELETE endpoint for course staff
  src/main/java/edu/ucsb/cs156/organic/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/organic/controllers/CoursesController.java
  src/test/java/edu/ucsb/cs156/organic/controllers/CoursesControllerTests.java
Labels: 10, Merge Candidate

#34 Added Interceptor and Test
  src/main/java/edu/ucsb/cs156/organic/Interceptors/RoleUserInterceptor.java
  src/main/java/edu/ucsb/cs156/organic/Interceptors/RoleUserInterceptorAppConfig.java
  src/test/java/edu/ucsb/cs156/organic/Interceptors/RoleUserInterceptorTests.java
  src/test/java/edu/ucsb/cs156/organic/testconfig/MockCurrentUserServiceImpl.java
Labels: 10, Merge Candidate

#48 Added Links for qa and prod
  README.md
Labels: 5

#27 CRUD Operations B2 - PUT and Controllers
  src/main/java/edu/ucsb/cs156/organic/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/organic/controllers/CoursesController.java
  src/main/java/edu/ucsb/cs156/organic/repositories/CourseRepository.java
  src/test/java/edu/ucsb/cs156/organic/controllers/CoursesControllerTests.java
  src/test/java/edu/ucsb/cs156/organic/controllers/JobsControllerTests.java
Labels: 10, Merge Candidate

#33 CRUD Operations B2 - DELETE and Controllers
  src/main/java/edu/ucsb/cs156/organic/controllers/CoursesController.java
  src/main/java/edu/ucsb/cs156/organic/repositories/StaffRepository.java
  src/test/java/edu/ucsb/cs156/organic/controllers/CoursesControllerTests.java
  src/test/java/edu/ucsb/cs156/organic/controllers/JobsControllerTests.java
Labels: 10, Merge Candidate

#36 CRUD Operations F3 - Edit Page
  frontend/src/App.js
  frontend/src/main/pages/Courses/CoursesEditPage.js
  frontend/src/main/pages/Courses/CoursesIndexPage.js
  frontend/src/stories/pages/Courses/CoursesEditPage.stories.js
  frontend/src/tests/pages/Courses/CoursesEditPage.test.js
  frontend/src/tests/pages/Courses/CoursesIndexPage.test.js
Labels: 10, Merge Candidate

#51 Added Course to Navbar
  frontend/src/App.js
  frontend/src/fixtures/currentUserFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/stories/components/Nav/AppNavbar.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
Labels: 10, Merge Candidate
